#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
from dataclasses import asdict
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.data.pressure_qdot_loader import (
    analyze_exported_condition_csv,
    generate_quality_report_markdown,
    load_pressure_qdot_manifest,
)


def _write_csv(path: Path, rows: list[dict], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Audit time-axis and invalid-segment quality for exported pressure/Qdot CSV files.")
    parser.add_argument(
        "--manifest-json",
        type=str,
        default="./data/pressure_qdot_csv/manifest.json",
        help="Manifest JSON generated by export_pressure_qdot_csv.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="./outputs/audit_pressure_qdot",
        help="Directory to save quality audit artifacts.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest = load_pressure_qdot_manifest(args.manifest_json)
    summaries = []
    invalid_segments = []
    for condition in manifest["conditions"]:
        summary, segments = analyze_exported_condition_csv(condition["condition_id"], condition["csv_path"])
        summaries.append(summary)
        invalid_segments.extend(segments)

    _write_csv(
        output_dir / "quality_summary.csv",
        [
            {
                "工况编号": summary.condition_id,
                "CSV路径": summary.csv_path,
                "总行数": summary.total_rows,
                "起始时间_秒": summary.time_start,
                "结束时间_秒": summary.time_end,
                "持续时长_秒": summary.duration_seconds,
                "最小时间步长_秒": summary.dt_min_seconds,
                "中位时间步长_秒": summary.dt_median_seconds,
                "最大时间步长_秒": summary.dt_max_seconds,
                "重复时间行数": summary.duplicate_time_rows,
                "非递增时间行数": summary.non_increasing_time_rows,
                "含任意零值的行数": summary.any_zero_rows,
                "Qdot含任意零值的行数": summary.qdot_any_zero_rows,
                "Qdot全零行数": summary.qdot_all_zero_rows,
                "Qdot全零段数": summary.qdot_all_zero_segments,
                "Qdot全零最长段长度_行": summary.qdot_all_zero_max_segment_len,
                "Qdot每行零通道数_均值": summary.qdot_zero_channel_count_mean,
                "Qdot每行零通道数_中位数": summary.qdot_zero_channel_count_median,
                "Qdot每行零通道数_最大值": summary.qdot_zero_channel_count_max,
                "压力全101325行数": summary.p_all_baseline_rows,
                "压力全101325段数": summary.p_all_baseline_segments,
                "压力全101325最长段长度_行": summary.p_all_baseline_max_segment_len,
                "Qdot首次非零时间_秒": summary.first_nonzero_qdot_time,
                "压力首次脱离101325时间_秒": summary.first_nonbaseline_pressure_time,
            }
            for summary in summaries
        ],
        [
            "工况编号",
            "CSV路径",
            "总行数",
            "起始时间_秒",
            "结束时间_秒",
            "持续时长_秒",
            "最小时间步长_秒",
            "中位时间步长_秒",
            "最大时间步长_秒",
            "重复时间行数",
            "非递增时间行数",
            "含任意零值的行数",
            "Qdot含任意零值的行数",
            "Qdot全零行数",
            "Qdot全零段数",
            "Qdot全零最长段长度_行",
            "Qdot每行零通道数_均值",
            "Qdot每行零通道数_中位数",
            "Qdot每行零通道数_最大值",
            "压力全101325行数",
            "压力全101325段数",
            "压力全101325最长段长度_行",
            "Qdot首次非零时间_秒",
            "压力首次脱离101325时间_秒",
        ],
    )

    _write_csv(
        output_dir / "invalid_segments.csv",
        [
            {
                "工况编号": seg.condition_id,
                "CSV路径": seg.csv_path,
                "信号类型": seg.signal_kind,
                "异常段类型": seg.segment_kind,
                "起始行号": seg.start_row,
                "结束行号": seg.end_row,
                "段长度_行": seg.length_rows,
                "起始时间_秒": seg.start_time,
                "结束时间_秒": seg.end_time,
            }
            for seg in invalid_segments
        ],
        [
            "工况编号",
            "CSV路径",
            "信号类型",
            "异常段类型",
            "起始行号",
            "结束行号",
            "段长度_行",
            "起始时间_秒",
            "结束时间_秒",
        ],
    )

    report = generate_quality_report_markdown(summaries, invalid_segments)
    (output_dir / "quality_report.md").write_text(report, encoding="utf-8")

    print("Quality audit finished.")
    print(f"Output dir: {output_dir}")
    print(f"Summary: {output_dir / 'quality_summary.csv'}")
    print(f"Segments: {output_dir / 'invalid_segments.csv'}")
    print(f"Report: {output_dir / 'quality_report.md'}")


if __name__ == "__main__":
    main()
